### ISSUE TITLE
Missing install step in guide from dbm docs

### ISSUE THREAD

**Issue by erichelgeson** [grails-guides/grails-database-migration#5]
from https://grails-plugins.github.io/grails-database-migration/latest/index.html

> It is also recommended to add a direct dependency to liquibase because Spring Boot overrides the one provided by this plugin
> 
> dependencies {
>    ...
>      compile 'org.liquibase:liquibase-core:3.6.1'
> }
>

**Comment by niravassar** [comment]
This is due to Gradle 5 not pulling in transitive dependencies. I have fixed it, also with some documentation changes. I ran it all the way through on a fresh app, all the commands in the guide are working.

639ce71e
